spring:
  profiles: default
  application:
    name: search-service
  cloud:
    config:
      profile: dev
      uri: http://localhost:8888/
      fail-fast: true
  data:
    elasticsearch:
      cluster-name: es-cluster
      cluster-nodes: 192.168.1.139:9100
      repositories:
        enabled: true
      local: false
      properties:
        path: ./elasticsearch/log      #elasticsearch日志存储目录
        data: ./elasticsearch/data    #elasticsearch数据存储目录

server:
  port: 1003

#logging:
  #level:
  #  org.springframework: debug


