spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yanglangfei/cloud-config
          password: wz5899117
          username: 185601452@qq.com
          search-paths: /config
          basedir: base/config-server/target/config
    bus:
      enabled: false
server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/

