spring:
  profiles: default
  application:
    name: pusht-service
  cloud:
    config:
      profile: dev
      uri: http://localhost:8888/
      fail-fast: true

server:
  port: 1008
logging:
  level: debug
