spring:
  application:
    name: gateway
  cloud:
    config:
      profile: dev
      uri: http://localhost:8888
      fail-fast: true

server:
  port: 1101

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    app:
      path: /app/**
      serviceId: app
    user-service:
      path: /user/**
      serviceId: user-service
    product-service:
      path: /product/**
      url: http://192.168.1.31:8080

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000