spring:
  application:
    name: gateway
  cloud:
    config:
      profile: dev
      uri: http://localhost:8888
      fail-fast: true

server:
  port: 1101


eureka:
  instance:
    ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

zuul:
  routes:
    app:
      path: /app/**
      serviceId: app
    user-service:
      path: /user/**
      serviceId: user-service
    product-service:
      path: /product/**
      url: http://192.168.1.31:8080