spring:
  application:
    name: app
  cloud:
    config:
      profile: dev
      uri: http://localhost:8888
      fail-fast: true
  http:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
server:
  port: 8084
logging:
  level: debug


feign:
  hystrix:
    enabled: false   #禁用 feign 断路超时，解决第一次访问超时