spring:
  application:
    name: app
  cloud:
    config:
      profile: dev
      uri: http://localhost:8888
      fail-fast: true
server:
  port: 8084
logging:
  level: debug

eureka:
  instance:
    ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    health-check-url-path: /health

