spring:
  application:
    name: web-yf
  cloud:
    config:
      profile: dev
      uri: http://localhost:8888
      fail-fast: true
  datasource:
    primary:
      url: dbc:mysql://121.40.227.121:3306/yfApp?useUnicode=true&characterEncoding=UTF-8
      username: master1
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
    shiro:
      url: dbc:mysql://121.40.227.121:3306/yfApp?useUnicode=true&characterEncoding=UTF-8
      username: master1
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
  redis:
    shiro:
      host: 127.0.0.1
      port: 6379
      timeout: 0
      password: admin
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false    #开发时关闭缓存,不然没法看到实时页面

server:
  port: 8801
