spring:
  application:
    name: discover

server:
  port: 1001

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    lease-renewal-interval-in-seconds: 2    #心跳检测时间间隔
    lease-expiration-duration-in-seconds: 5  #5秒没检测到清除service
#security:
 # basic:
  #  enabled: false
  #user:
  #  name: root
  #  password: 111111

