spring:
  application:
    name: admin
  cloud:
    config:
      profile: dev
      uri: http://localhost:8888
      fail-fast: true
  boot:
    admin:
      notify:
        mail:
          enabled: true    #开启邮件通知
          ignore-changes: "UNKNOWN:UP"  #忽略状态
          to: 185601452@qq.com   #接受邮件地址
          cc: xxxxxxx@qq.com    #抄送人
          from: 185601452@qq.com  #发件人
          subject: "#{application.name} (#{application.id}) is #{to.status}"   #主题
          text: "#{application.name} (#{application.id})\nstatus changed from #{from.status} to #{to.status}\n\n#{application.healthUrl}"
      monitor:
        period: 100000   #更新频率
        status-lifetime: 50000   #被监控的应用信息的过期时间，单位毫秒

server:
  port: 8855



