spring:
  application:
    name: turbine
  cloud:
    config:
      profile: dev
      uri: http://localhost:8888
      fail-fast: true

server:
  port: 1115
turbine:
  app-config: user-service,product-service,gateway,app,discover,config-server
  stream:
    port: 8989


eureka:
  instance:
    preferIpAddress: true

management:
  security:
    enabled: true
security:
  basic:
    enabled: false
  user:
    name: admin
    password: admin123
hystrix.stream.dashboard.intervalInMilliseconds: 5000