spring:
  application:
    name: turbine
  cloud:
    config:
      profile: dev
      uri: http://localhost:8888
      fail-fast: true

server:
  port: 1118
turbine:
  aggregator:
    clusterConfig: default
  app-config: product-service
  clusterNameExpression: default
  combine-host-port: true



management:
 # security:
 #   enabled: true
  port: 8990
#security:
 # basic:
  #  enabled: false
  #user:
  #  name: admin
   # password: 111111
hystrix.stream.dashboard.intervalInMilliseconds: 5000
